#!/bin/bash
# your code goes here
git clone https://github.com/vcyzteen/linux.git
cd linux
git fetch https://github.com/Tomoms/android_kernel_oppo_msm8974.git
git cherry-pick 11647f99b4de6bc460e106e876f72fc7af3e54a6
git push https://$GITHUB_TOKEN@github.com/vcyzteen/linux.git
# wget https://raw.githubusercontent.com/vcyzteen/myscripts/master/kernel.sh
# bash kernel.sh
