#!/bin/bash
# your code goes here
mkdir rembg && cd rembg
pip install rembg
curl -s https://cdn.donmai.us/original/1c/4b/__fu_hua_and_fu_hua_honkai_and_1_more_drawn_by_huahong2333__1c4b8cf8943f3240feee8a9e7d496849.jpg | rembg > output.jpg
